/* automatically generated by rust-bindgen */

pub const true_: u32 = 1;
pub const false_: u32 = 0;
pub const __bool_true_false_are_defined: u32 = 1;
extern "C" {
    pub fn oss_remove(filename: *const ::std::os::raw::c_char) -> bool;
}
extern "C" {
    #[doc = " compress file from src to dest"]
    pub fn oss_compress(src: *const ::std::os::raw::c_char, dest: *const ::std::os::raw::c_char);
}
extern "C" {
    #[doc = " decompress file from src to dest"]
    pub fn oss_decompress(src: *const ::std::os::raw::c_char, dest: *const ::std::os::raw::c_char);
}
